name: Hello Spring CI

on:
  #   workflow_dispatch:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Test
        working-directory: docker/app1-hello/springboot/hello-spring
        run: mvn -B clean verify

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: docker/app1-hello/springboot/hello-spring/target/surefire-reports

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Jar for docker
        working-directory: docker/app1-hello/springboot/hello-spring
        run: mvn -B clean package -DskipTests

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: built and push docker image
        uses: docker/build-push-action@v3
        with:
          context: docker/app1-hello/springboot/hello-spring
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-spring:latest
